custom_imports = dict(
    imports=[
        'dataset',
        'model.segmentor.bev_segmentor_lidar_3d',
        'model.lifter.gaussian_lifter',
        'model.encoder.gaussian_encoder.gaussian_mamba_encoder',
        'model.encoder.gaussian_encoder.gaussian_gaf_mamba_encoder',
        'model.head.depth_head',
        'model.detector.yolo26_online',
        'model.detector.yolo_2d_to_3d_lifter',
        'model.detector.object_gaussian_seed_completion',
        'model.detector.box_gaussian_completion',
        'loss.box_hypothesis_loss',
    ],
    allow_failed_imports=False,
)

_base_ = [
    './_base_/misc.py',
    './_base_/model.py',
    './_base_/occ3d_pcd_dfa3d.py',
]

# =========== data config ==============
# DAOcc uses 256x704 images. GaussianFormer3D's loader keeps the original image size unless
# ResizeCropFlipImage is enabled in config/_base_/occ3d_pcd_dfa3d.py, so this
# debug config actually feeds 704x256 images into the image backbone/FPN.
input_shape = (704, 256)

# Offline YOLO2D cache generated by tools/generate_yolo2d_cache.py.
# Coordinates are post ResizeCropFlipImage, i.e. network image coords 704x256.
yolo2d_cache_train = 'data/nuscenes_cam/yolo2d_cache/yolo26m_final_rgbfix_train.pkl'
yolo2d_cache_val = 'data/nuscenes_cam/yolo2d_cache/yolo26m_final_rgbfix_val.pkl'
yolo2d_cache_max_det = 100

# =========== misc config ==============
# Debug version: GAF-Mamba and GaussianProbe each follow print_freq-style debugging:
# one debug print every 50 forwards, capped at 5 prints on rank0.
optimizer = dict(
    optimizer=dict(
        type='AdamW', lr=1.5e-4, weight_decay=0.01,
    ),
    paramwise_cfg=dict(
        custom_keys={
            'img_backbone': dict(lr_mult=0.1),
        }
    ),
)
grad_max_norm = 35
max_epochs = 24  # keep the same 24-epoch LR schedule; epoch 4 is the quick-screen checkpoint
# Evaluation cadence. 1 = evaluate every epoch; 2 = every 2 epochs; 0 or negative = skip eval.
# You can also override this from train.py with: --eval-every-epochs N
eval_every_epochs = 4  # quick screen at epoch 4 while preserving the 24-epoch schedule
# Mamba-only encoder no longer consumes image/depth branch parameters.
# Keep this true for DDP safety if any frozen/unused legacy modules remain in the model.
find_unused_parameters = True

# ========= debug switches ===============
# Module-level debug remains in each module config below.  Normal V11 runs
# keep only object_gaussian_seed_completion debug enabled.
# This switch only controls the train.py auxiliary-loss connection debug.
aux_loss_debug = dict(
    enabled=False,
    interval=200,
    max_print=0,
)
# Safety fallback for auxiliary scalar losses returned by modules.
aux_loss_manual_fallback = True

# Prints the detection-GT fields that actually survive dataloader/collate and
# are passed to BEVSegmentorLiDAR3D.forward(metas=data).  Use this to diagnose
# batches where perfect-2D/OQG supervision cannot find 3D GT boxes.
gt_data_debug = dict(
    enabled=False,
    interval=200,
    max_print=0,
    show_all_keys=False,
)

# Raw pkl parser debug. Keep off for normal training; enable only when checking
# dataset annotation fields.
dataset_gt_raw_debug = dict(
    enabled=False,
    interval=1,
    max_print=0,
    only_when_problem=True,
    show_info_keys=False,
    show_value_summaries=False,
)

# ========= Occ3D loss config ===============
# Occ3D-nuScenes: 18 labels, 0-16 semantic classes, 17 = free/empty.
loss = dict(
    type='MultiLoss',
    loss_cfgs=[
        dict(
            type='OccupancyLoss',
            weight=1.0,
            empty_label=17,
            num_classes=18,
            use_focal_loss=False,
            use_dice_loss=False,
            balance_cls_weight=True,
            multi_loss_weights=dict(
                loss_voxel_ce_weight=10.0,
                loss_voxel_lovasz_weight=1.0,
            ),
            use_sem_geo_scal_loss=False,
            use_lovasz_loss=True,
            lovasz_ignore=17,
            manual_class_weight=[
                1.01552756, 1.06897009, 1.30013094, 1.07253735, 0.94637502, 1.10087012,
                1.26960524, 1.06258364, 1.18901900, 1.06217292, 1.00595144, 0.85706115,
                1.03923299, 0.90867526, 0.89364310, 0.85486129, 0.85278290, 0.50000000,
            ],
        ),
        # V24-I auxiliary decoder supervision.
        # The penultimate decoder is rendered on a deterministic 3D checkerboard
        # quarter-volume subset. CE-only supervision avoids duplicating the
        # expensive full-grid Lovasz and residual U-Net path.
        dict(
            type='OccupancyLoss',
            # BaseLoss and OccupancyLoss each apply this configured weight.
            # sqrt(0.30) therefore gives the previous V24-I effective weight 0.30.
            weight=0.54772256,
            empty_label=17,
            num_classes=18,
            use_focal_loss=False,
            use_dice_loss=False,
            balance_cls_weight=True,
            multi_loss_weights=dict(
                loss_voxel_ce_weight=10.0,
                loss_voxel_lovasz_weight=0.0,
            ),
            use_sem_geo_scal_loss=False,
            use_lovasz_loss=False,
            lovasz_ignore=17,
            manual_class_weight=[
                1.01552756, 1.06897009, 1.30013094, 1.07253735, 0.94637502, 1.10087012,
                1.26960524, 1.06258364, 1.18901900, 1.06217292, 1.00595144, 0.85706115,
                1.03923299, 0.90867526, 0.89364310, 0.85486129, 0.85278290, 0.50000000,
            ],
            input_dict=dict(
                pred_occ='pred_occ_aux',
                sampled_xyz='sampled_xyz_aux',
                sampled_label='sampled_label_aux',
                occ_mask='occ_mask_aux',
            ),
        ),
        # V12 learns whether each projected measured Gaussian belongs to the
        # matched 2D object.  This directly supervises the new ownership MLP.
        dict(type='ScalarTensorLoss', input_key='loss_gaussian_owner', weight=0.50),
        # V14 keeps V12 geometry fixed and learns only whether each generated
        # Gaussian is non-empty and semantically reliable.  The small weight
        # keeps this auxiliary objective from competing with occupancy loss.
        dict(type='ScalarTensorLoss', input_key='loss_gaussian_child_quality', weight=0.05),
        # Post-Mamba voxel geometry auxiliary loss. The main OccupancyLoss still
        # supervises the final 18-class logits; this term only stabilizes the
        # occupied-vs-empty branch of the residual 3D U-Net.
        dict(type='ScalarTensorLoss', input_key='loss_unet_geometry', weight=0.50),
    ],
)

loss_input_convertion = dict(
    pred_occ='pred_occ',
    sampled_xyz='sampled_xyz',
    sampled_label='sampled_label',
    occ_mask='occ_mask',
    pred_occ_aux='pred_occ_aux',
    sampled_xyz_aux='sampled_xyz_aux',
    sampled_label_aux='sampled_label_aux',
    occ_mask_aux='occ_mask_aux',
    loss_gaussian_owner='loss_gaussian_owner',
    loss_gaussian_child_quality='loss_gaussian_child_quality',
    loss_unet_geometry='loss_unet_geometry',
)

# ========= model config ===============
embed_dims = 128
num_decoder = 4
num_single_frame_decoder = 1

# Occ3D-nuScenes official occupancy range/grid.
pc_range = [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4]
# Used only by 7D visibility / free-space / measured octree Gaussian generation.
# Keep X/Y larger than Occ3D supervision to avoid semantic truncation near the border,
# and extend Z to Occ3D's top boundary so measured Gaussians can cover all GT voxels.
visibility_pc_range = [-54.0, -54.0, -5.0, 54.0, 54.0, 5.4]
# DAOcc octree cells are aligned around the visibility range.
# Z upper is 7.2 instead of 5.4 so the vertical span is 12.8m, divisible by
# all octree Gaussian levels: 3.2 / 1.6 / 0.8 / 0.4.
octree_pc_range = [-54.4, -54.4, -5.6, 54.4, 54.4, 7.2]
occ_size = [200, 200, 16]
grid_size = 0.4
voxel_size = [0.075, 0.075, 0.2]

# Gaussian scale range: smaller than SurroundOcc because Occ3D covers 80m x 80m.
scale_range = [0.01, 1.44]
xyz_coordinate = 'cartesian'
phi_activation = 'sigmoid'
include_opa = True
# R50 image backbone is initialized inside model.img_backbone.init_cfg.
# Do not load the old R101-DCN whole-model checkpoint after switching backbone depth.
load_from = None
r50_backbone_checkpoint = 'ckpts/htc_r50_backbone.pth'
semantics = True
# Occ3D official label space: 0-16 semantic classes, 17 = free/empty.
# This keeps the extra "others" class at index 0 so results are comparable with
# Occ3D Table II style evaluation.
semantic_dim = 17
occ3d_semantic_class_names = [
    'others', 'barrier', 'bicycle', 'bus', 'car', 'construction_vehicle',
    'motorcycle', 'pedestrian', 'traffic_cone', 'trailer', 'truck',
    'driveable_surface', 'other_flat', 'sidewalk', 'terrain', 'manmade', 'vegetation',
]
occ3d_debug_class_ids = (1, 2, 5, 6, 7, 8)

# ========= visualization config ===============
# Gaussian completion visualization: when enabled, one trigger saves two PNGs
# per selected sample: measured-only and measured+completed.
gaussian_completion_visualizer = dict(
    enabled=False,
    out_dir='gaussian_completion_debug',
    interval=50,
    max_outputs=0,
    batch_indices=(0,),
    point_cloud_range=pc_range,
    scale_range=scale_range,
    z_range=(-5.0, 5.4),
    save_ply=False,
    save_png=False,
    ellipsoid_latitude_segments=4,
    ellipsoid_longitude_segments=6,
    max_gaussians_per_ply=0,
    save_lidar_points=True,
    point_xyz_dims=(0, 1, 2),
    point_current_flag_dim=6,
    point_time_lag_dim=4,
    current_time_eps=1.0e-3,
    point_stride=1,
    max_points_per_ply=0,
    history_point_color=(105, 105, 115),
    current_point_color=(220, 0, 255),
    level_values=(3.2, 1.6, 0.8, 0.4),
    level_tolerance=0.08,
    infer_level_from_scale=True,
    level_32_color=(60, 220, 255),
    level_16_color=(60, 220, 80),
    level_08_color=(40, 120, 255),
    level_04_color=(255, 50, 50), 
    measured_unknown_color=(220, 0, 255),
    # Completed Gaussians are all orange.
    completed_color=(255, 145, 0),
    debug_print=False,
    # Print skip reasons from GaussianCompletionVisualizer.
    # This is the switch to disable once visualization is confirmed.
    debug_skip=False,
    debug_max_print=0,
    debug_interval=50,
    startup_log=False,
)


# Sparse-UVD GAF uses LiDAR-projected depth_gt directly as a GTDpt depth prior.
# DepthHead_GTDpt converts depth_gt into multi-scale depth distributions; it is
# not a learnable depth predictor, so no DepthAuxLoss is used in this config.
d_bound = [2.0, 58, 0.5]
downsample_factors = [8, 16, 32, 64]
dice_layer_depthnet = 2
indice_layer_depthnet = 2
depth_loss_weight = 0.0  # unused for DepthHead_GTDpt

model = dict(
    type='BEVSegmentorLiDAR3D',
    freeze_img_backbone=True,
    freeze_img_neck=False,
    use_grid_mask=False,
    skip_img_depth_branch=False,
    use_img_branch=True,
    use_depth_branch=True,
    d_bound=d_bound,
    dpt_debug=False,
    dpt_debug_interval=200,
    dpt_debug_max_print=2,
    gaussian_completion_visualizer=gaussian_completion_visualizer,
    pts_dpt_head=dict(
        type='DepthHead_GTDpt',
        in_channels=embed_dims,
        cam_channel=0,
        mid_channels=embed_dims,
        out_channels=0,
        downsample_factor=downsample_factors[indice_layer_depthnet],
        dbound=d_bound,
        loss_weight=depth_loss_weight,
        num_cams=6,
        max_tol=0,
        sfm_or_sig=True,
        indice_layer=indice_layer_depthnet,
    ),

    online_yolo=dict(
        enabled=False,
        weights='ckpts/yolo26m.pt',
        class_mode='coco',  # smoke-test only. Real route uses offline_yolo2d cache below.
        max_det=80,
        conf_small=0.15,
        conf_vehicle=0.25,
        imgsz=(256, 704),
        debug=False,
        debug_interval=200,
        debug_max_print=0,
    ),
    offline_yolo2d=dict(
        enabled=True,
        # Keep this on but sparse.  Dataset-level per-sample cache prints are
        # disabled below because each DataLoader worker has its own counter and
        # otherwise it floods stdout during prefetch.
        debug=False,
        debug_interval=100,
        debug_max_print=0,
        # Speed guard for the real YOLO2D -> OQG -> boxhyp route.
        # Shapes remain [B,6,100,*], but only the top-score boxes stay valid.
        max_boxes_per_sample=72,
        max_boxes_per_cam=32,
        # v8.7.4: project GT 3D boxes to each camera and match cached YOLO2D
        # boxes by same-class 2D IoU.  The matched GT index supervises OQG
        # center/size/yaw/rank losses in the real YOLO-cache route.
        gt_supervision=True,
        gt_match_min_iou=0.05,
        gt_match_class_aware=True,
        gt_match_min_area=4.0,
        gt_match_clip=True,
        gt_match_debug=False,
        gt_match_debug_interval=100,
        gt_match_debug_max_print=0,
    ),
    # v9.1 diagnostic: GT 3D boxes are projected to perfect 2D boxes, then OQG
    # predicts boxhyp 3D boxes.  BoxGaussianCompletion still uses source='boxhyp',
    # so this isolates YOLO detection noise without using GT 3D boxes for completion.
    gt_projected_2d=dict(
        enabled=False,
        max_det=120,
        score=1.0,
        min_depth=1.0e-3,
        min_visible_corners=1,
        min_box_area=4.0,
        clip=True,
        debug=False,
        debug_interval=100,
        debug_max_print=0,
    ),
    # Legacy rule-based proposal lifting.  Keep disabled in the OQG-lite route;
    # it remains in the codebase only as a baseline/fallback for comparison.
    yolo_2d_to_3d_lifter=dict(
        enabled=False,
        num_depth_hypotheses=9,
        point_cloud_range=pc_range,
        depth_bound=d_bound,
        anchor_weights=(0.50, 0.65, 0.80, 0.95, 1.00, 0.95, 0.80, 0.65, 0.50),
        use_size_depth_prior=True,
        num_fixed_depth_anchors=4,
        default_fy=554.0,
        min_fy=250.0,
        max_fy=900.0,
        bottom_center_v_offset_ratio=0.03,
        use_box_bottom_center=True,
        center_z_from_bottom=False,
        z_mode='class_center',
        z_filter_mode='clamp',
        xy_generation_mode='bev_ray',
        xy_filter_mode='clamp',
        pc_range_xy_margin=4.0,
        ground_z=-1.0,
        yaw_mode='ray',
        min_box_size_px=2.0,
        debug=False,
        debug_interval=100,
        debug_max_print=0,
        debug_lifting_eval=False,
        eval_center_thresholds=(0.5, 1.0, 2.0, 4.0),
    ),
    # Legacy OQG block retained only for rollback compatibility.  It is not
    # instantiated, supervised, or consumed anywhere in V22-B.
    object_center_query_lifter=dict(
        enabled=False,
        num_depth_hypotheses=12,
        point_cloud_range=pc_range,
        depth_bound=d_bound,
        img_feat_channels=embed_dims,
        embed_dims=embed_dims,
        hidden_dims=192,
        feature_level=0,
        depth_level=0,
        num_depth_from_dpt=4,
        num_size_depth_candidates=4,
        num_fixed_depth_candidates=4,
        min_depth_prob_weight=1.0e-4,
        default_fy=554.0,
        min_fy=250.0,
        max_fy=900.0,
        min_box_size_px=2.0,
        box_center_v_ratio=0.50,
        use_bottom_point=True,
        bottom_center_v_offset_ratio=0.03,
        pc_range_xy_margin=4.0,
        xy_filter_mode='clamp',
        residual_center_scale=(3.0, 3.0, 1.0),
        residual_center_hard_limit=(8.0, 8.0, 2.0),
        residual_log_size_scale=0.30,
        residual_log_size_hard_limit=0.35,
        residual_yaw_scale=0.60,
        use_2d_center_offset=True,
        center2d_offset_scale=(0.35, 0.30),
        depth_log_residual_scale=0.25,
        depth_log_residual_hard_limit=0.35,
        score_init_bias=-1.5,
        train_with_gt=True,
        center_loss_weight=1.0,
        size_loss_weight=0.20,
        yaw_loss_weight=0.05,
        obj_loss_weight=0.35,
        depth_loss_weight=0.20,
        reproj_loss_weight=0.10,
        reproj_min_depth=1.0e-3,
        use_direct_topk=True,
        # OQG keeps its original candidate set and auxiliary losses.  V10.0
        # overwrites the selected proposal tensors after foreground-depth lifting.
        direct_topk_per_box=1,
        direct_selected_score_thr=0.005,
        use_listwise_rank_loss=True,
        rank_loss_weight=0.50,
        rank_tau=1.5,
        use_hard_best_rank_loss=True,
        hard_rank_loss_weight=0.35,
        hard_rank_max_dist=80.0,
        # v8.7.4: weak negative supervision for YOLO boxes that do not match any
        # projected GT.  This discourages false-positive boxes from entering
        # OQG top-k completion.
        unmatched_obj_loss_weight=0.10,
        unmatched_obj_max_rows=256,
        # Soft-argmax is only a weak auxiliary loss.  Multi-depth candidates are
        # multi-modal, so a large soft-center loss can average good hypotheses
        # into a bad midpoint and hurt top-1 ranking.
        soft_argmax_center_loss_weight=0.05,
        soft_argmax_temperature=1.0,
        score_target_close_dist=1.0,
        score_target_mid_dist=2.0,
        score_target_far_dist=4.0,
        score_target_close_value=1.0,
        score_target_mid_value=0.7,
        score_target_far_value=0.3,
        best_candidate_min_score_target=0.2,
        max_eval_center_error=80.0,
        valid_loss_weight=1.0,
        debug=False,
        detach_box_outputs=True,
        detach_img_features=True,
        # V10.0 disables the v9.5 hand-written candidate re-ranking.  The new
        # FrustumGeometryLifter directly generates a foreground-supported center.
        geometry_rerank_enabled=False,
        geometry_score_weight=0.75,
        geometry_core_shrink=0.08,
        geometry_min_points=2,
        geometry_max_points_per_box=512,
        geometry_box_expand_xy=1.25,
        geometry_box_expand_z=1.35,
        geometry_support_norm=6.0,
        geometry_near_sigma=1.5,
        geometry_current_weight=1.0,
        geometry_history_weight_dynamic=0.25,
        geometry_history_weight_static=0.70,
        geometry_dynamic_class_ids=(0, 1, 2, 3, 4, 6, 7, 8),
        geometry_static_class_ids=(5, 9),
        debug_interval=100,
        debug_max_print=12,
        debug_lifting_eval=False,
        eval_center_thresholds=(0.5, 1.0, 2.0, 4.0),
    ),
    # V10/V10.2 rigid-box route is disabled in V11 and retained only for rollback.
    # Fixed V10 foreground-depth initialization followed by a compact
    # point-wise frustum refiner.  One coherent initial box is jointly corrected
    # in center, size and yaw; there is no V10.1 multi-center weighted mixture.
    frustum_geometry_lifter=dict(
        enabled=False,
        point_cloud_range=pc_range,
        # Fixed V10 initial box.
        core_shrink_x=0.12,
        core_shrink_top=0.10,
        core_shrink_bottom=0.18,
        context_expand=0.10,
        min_points=2,
        min_points_small=1,
        max_points_per_box=768,
        cluster_gap_abs=0.75,
        cluster_gap_rel=0.025,
        cluster_gap_large_scale=1.35,
        cluster_gap_small_scale=0.80,
        max_clusters=5,
        cluster_support_norm=5.0,
        cluster_std_scale=1.25,
        context_depth_margin=0.60,
        foreground_near_scale=8.0,
        min_cluster_quality=0.16,
        current_weight=1.0,
        history_weight_dynamic=0.18,
        history_weight_static=0.70,
        dynamic_max_time_lag=0.35,
        min_current_points_for_dynamic=1,
        center_xy_blend=0.88,
        center_z_blend=0.0,
        surface_offset_ratio=0.20,
        score_geometry_weight=0.55,
        selected_score_thr=0.005,
        dynamic_class_ids=(0, 1, 2, 3, 4, 6, 7, 8),
        static_class_ids=(5, 9),
        small_class_ids=(5, 6, 7, 8, 9),
        large_class_ids=(1, 2, 3, 4),
        # PointNet-style full-box refiner.
        refiner_num_points=128,
        refiner_min_points=3,
        refiner_min_points_small=1,
        refiner_context_expand=0.08,
        dynamic_refiner_max_time_lag=0.50,
        point_hidden_dims=128,
        box_hidden_dims=192,
        class_embed_dims=16,
        center_residual_scale=(2.0, 2.0, 0.75),
        log_size_residual_scale=(0.35, 0.35, 0.25),
        yaw_residual_scale=1.57079632679,
        score_quality_weight=0.20,
        train_with_gt=True,
        gt_box_expand=(1.10, 1.10, 1.15),
        point_mask_loss_weight=0.35,
        center_loss_weight=1.00,
        size_loss_weight=0.55,
        yaw_loss_weight=0.35,
        corner_loss_weight=0.25,
        quality_loss_weight=0.10,
        residual_regularization_weight=0.01,
        detach_box_outputs=True,
        debug=False,
        debug_interval=100,
        debug_train_max_print=0,
        debug_eval_max_print=0,
        eval_center_thresholds=(0.5, 1.0, 2.0),
    ),
    # V22-C2: V22-C1 visibility gating + decoupled geometry/semantic child quality.
    # There are no artificial total caps for object/local/generic completion.  Every
    # branch proposes according to its local per-object/per-parent rule, and the
    # only total limit is the actual remaining num_anchor=9000 capacity.
    object_gaussian_seed_completion=dict(
        enabled=True,
        point_cloud_range=pc_range,
        scale_range=scale_range,
        semantic_dim=semantic_dim,
        feature_dim=embed_dims,
        include_opa=include_opa,
        core_shrink_x=0.12,
        core_shrink_top=0.10,
        core_shrink_bottom=0.18,
        min_projected_gaussians=1,
        depth_cluster_gap_abs=0.90,
        depth_cluster_gap_rel=0.030,
        max_depth_clusters=6,
        support_norm=5.0,
        # Learned measured-Gaussian -> 2D-object ownership.
        owner_feature_dim=16,
        owner_class_dim=8,
        owner_hidden_dim=128,
        owner_threshold=0.60,
        owner_min_keep_score=0.38,
        owner_focal_alpha=0.75,
        owner_focal_gamma=2.0,
        owner_prior_strength=1.0,
        owner_semantic_prior_logit=3.0,
        inject_seed_semantics=True,
        inject_seed_features=True,
        # Local completion counts remain per owned parent.  These are not total
        # branch limits and may use all remaining 9000-slot capacity.
        generate_seed_children=True,
        seed_children_per_parent=3,
        small_seed_children_per_parent=4,
        large_seed_children_per_parent=4,
        child_offset_ratio=0.90,
        child_scale_ratio=0.62,
        min_gaussian_scale=0.04,
        max_gaussian_scale=0.32,
        completion_opacity=0.18,
        # Owner-weighted direct object-Gaussian completion.
        enable_object_completion=False,
        class_typical_dims=(
            (4.5, 1.8, 1.6), (7.0, 2.5, 3.0), (6.0, 2.6, 3.0),
            (10.0, 2.6, 3.2), (10.0, 2.6, 3.0), (2.0, 0.5, 0.8),
            (2.1, 0.8, 1.4), (1.8, 0.6, 1.5), (0.8, 0.8, 1.75),
            (0.5, 0.5, 0.8),
        ),
        object_children_min=(12, 20, 24, 24, 20, 8, 6, 6, 4, 2),
        object_children_max=(40, 56, 64, 64, 56, 24, 12, 12, 8, 4),
        object_merge_radii=(1.8, 2.6, 2.6, 3.0, 3.0, 1.2, 0.9, 0.9, 0.7, 0.5),
        object_scale_min=0.08,
        object_scale_max=0.60,
        object_completion_opacity=0.14,
        object_min_record_score=0.15,
        # V22-C2 retains V22-C1: build the same 3x3x3 visibility-neighborhood maps once per
        # batch on CUDA.  A Local child is hard-suppressed only when its CENTER
        # lies in STRONG_FREE.  Merely touching strong/weak free space in the
        # neighborhood causes only a bounded soft attenuation.  No 13-point
        # sampling, CPU traversal, sorting, or searchsorted is used.
        enable_visibility_gate=True,
        visibility_grid_range=visibility_pc_range,
        visibility_voxel_size=0.8,
        # Kept as a legacy config field for checkpoint/config compatibility;
        # V22-C2 does not use neighborhood ratio as a hard-reject threshold.
        visibility_strong_ratio_hard=0.25,
        visibility_strong_ratio_weight=0.35,
        visibility_weak_ratio_weight=0.15,
        visibility_soft_gate_min=0.50,
        visibility_gate_local_only=True,
        # Keep tensor shapes static. Center STRONG_FREE contradictions receive
        # a persistent render gate of zero instead of dynamic child compaction.
        visibility_filter_hard_reject=False,
        visibility_encoder_gain_power=0.50,
        visibility_debug=False,
        # Quality prediction never changes candidate position/scale/yaw and
        # never limits a branch's total count. V22-C2 separates geometry
        # existence from object-class correctness and allows zero gates.
        enable_child_quality=True,
        occ_empty_label=17,
        child_quality_feature_dim=24,
        child_quality_class_dim=8,
        child_quality_kind_dim=8,
        child_quality_hidden_dim=96,
        child_quality_prior_strength=1.0,
        child_quality_nonempty_weight=0.50,
        child_quality_semantic_weight=0.50,
        # V22-C2: q_geometry supervises non-empty existence; q_semantic is
        # class correctness conditioned on a non-empty sampled voxel. Geometry
        # controls opacity/persistent rendering, while geometry*semantic controls
        # object-class features and capacity ranking. All residual floors are zero.
        child_quality_decoupled=True,
        child_quality_semantic_on_nonempty_only=True,
        child_quality_geometry_zero_threshold=0.20,
        child_quality_semantic_zero_threshold=0.20,
        child_quality_persistent_geometry_gate=True,
        child_quality_opacity_floor=0.0,
        child_quality_feature_floor=0.0,
        child_quality_rank_floor=0.0,
        # Every non-owned reliable measured Gaussian can create its normal local
        # generic child.  No generic-branch total cap is applied.
        enable_generic_completion=True,
        generic_opacity_thr=0.35,
        generic_max_parent_scale=0.30,
        generic_children_per_parent=1,
        generic_child_offset_ratio=0.80,
        generic_child_scale_ratio=0.72,
        generic_completion_opacity=0.12,
        # OQG is disabled in V22-C2.  Legacy parameters below remain rollback-only;
        # there is no per-sample total cap other than the 9000-slot capacity.
        enable_oqg_fallback=False,
        fallback_score_thr=0.02,
        fallback_gaussians_per_box=1,
        fallback_scale_ratio=0.08,
        fallback_min_scale=0.08,
        fallback_max_scale=0.28,
        fallback_opacity=0.055,
        fallback_semantic_prior_logit=1.10,
        fallback_nms_default_radius=1.0,
        fallback_nms_class_radii=(1.8, 2.4, 2.4, 2.5, 2.5, 1.2, 0.8, 0.8, 0.7, 0.6),
        add_completion_feature=True,
        # Explicitly unlimited legacy cap fields.  The implementation ignores
        # branch totals and truncates only when the actual N=9000 slots are full.
        max_projected_gaussians_per_box=0,
        max_seed_parents_per_box=0,
        max_seed_parents_per_sample=0,
        seed_parent_caps=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
        max_local_gaussians=0,
        max_object_gaussians=0,
        max_generic_gaussians=0,
        max_completed_gaussians=0,
        fallback_max_per_sample=0,
        # One compact line every 100 calls; train/eval each keep 12 prints.  It
        # includes proposed count, capacity drops, and actual total/9000 usage.
        debug=False,
        debug_interval=100,
        debug_train_max_print=0,
        debug_eval_max_print=0,
    ),
    # Legacy rigid-box completion remains disabled in V11.1.  It remains in the config
    # only so V10 can be restored by switches without recovering an old file.
    box_gaussian_completion=dict(
        enabled=False,
        source='boxhyp',  # disabled legacy V10 rigid-box completion
        num_gaussians_per_box=4,
        small_num_gaussians_per_box=6,
        large_num_gaussians_per_box=8,
        max_completed_gaussians=0,
        max_boxes_per_sample=0,
        fill_capacity=False,
        adaptive_box_counts=False,
        box_budget_ratio=0.0,
        min_gaussians_per_box=1,
        max_gaussians_per_box=0,
        small_box_weight=2.0,
        large_box_weight=1.35,
        volume_weight=0.12,
        enable_local_completion=True,
        local_completion_ratio=0.0,
        local_children_per_parent=1,
        local_children_small_scale=1,
        local_children_medium_scale=0,
        local_children_large_scale=0,
        local_scale_small_threshold=0.55,
        local_scale_medium_threshold=1.10,
        local_offset_radius_small=0.16,
        local_offset_radius_medium=0.24,
        local_offset_ratio=1.25,
        local_scale_ratio=0.55,
        local_completion_opacity=0.18,
        local_max_parents=0,
        exclude_local_inside_boxes=True,
        measured_child_completion=True,
        box_children_per_parent=5,
        dense_fill_remaining=False,
        sparse_box_anchor_enabled=True,
        box_match_margin_xy=0.45,
        box_match_margin_z=0.30,
        point_cloud_range=pc_range,
        scale_range=scale_range,
        box_dim_order='lwh',
        z_origin='center',
        template_extent=0.30,
        scale_ratio=0.11,
        min_gaussian_scale=0.04,
        max_gaussian_scale=0.35,
        completion_opacity=0.22,
        semantic_dim=semantic_dim,
        semantic_prior_logit=3.0,
        add_completion_feature=True,
        feature_dim=embed_dims,
        small_class_ids=(5, 6, 7, 8, 9),  # DAOcc ids: barrier/motorcycle/bicycle/pedestrian/traffic_cone
        large_class_ids=(1, 2, 3, 4),  # DAOcc ids: truck/construction_vehicle/bus/trailer; car keeps base count
        small_first=True,
        use_gt_ann_mask=True,
        proposal_score_thr=0.03,
        proposal_require_valid=True,
        proposal_topk_per_sample=180,
        # v9.4: class-wise center-distance NMS before Gaussian completion.
        # This removes multi-view duplicate OQG boxes from Perfect2D projections.
        proposal_nms_enabled=True,
        proposal_nms_max_boxes_per_sample=120,
        proposal_nms_use_xy=True,
        proposal_nms_max_z_diff=2.0,
        proposal_nms_default_radius=1.2,
        proposal_nms_class_radii=(
            1.8,  # car
            2.4,  # truck
            2.4,  # construction_vehicle
            2.5,  # bus
            2.5,  # trailer
            1.2,  # barrier
            0.8,  # motorcycle
            0.8,  # bicycle
            0.7,  # pedestrian
            0.6,  # traffic_cone
        ),
        # Small-target diagnosis is off by default to save memory/time.
        # Re-enable only when checking Occ3D-17 mapping or Gaussian/voxel alignment.
        debug=False,
        debug_interval=100,
        debug_max_print=0,
        summary_debug=False,
        semantic_debug=False,
        semantic_debug_class_ids=(1, 2, 5, 6, 7, 8),
        gt_voxel_hit_debug=False,
        gt_voxel_hit_debug_class_ids=(1, 2, 5, 6, 7, 8),
        gt_voxel_hit_topk_labels=4,
        # Diagnostic switch for the next ablation: set True to keep only box-guided children
        # and remove local measured-child completion without touching code.
        diagnostic_disable_local_completion=False,
    ),
    voxelize_lidar=dict(
        max_num_points=10,
        point_cloud_range=pc_range,
        voxel_size=voxel_size,
        max_voxels=[120000, 160000],
    ),
    lidar_voxel_encoder=dict(
        type='HardSimpleVFE',
        num_features=6,
    ),
    img_backbone_out_indices=[0, 1, 2, 3],
    # Memory-saving image backbone.  The uploaded DAOcc/HTC checkpoint has standard
    # ResNet-50 bottleneck keys such as conv1.*, bn1.*, layer1.*, ...,
    # so it should be loaded as the image backbone init_cfg instead of the old
    # r101_dcn_fcos3d_pretrain whole-model checkpoint.
    img_backbone=dict(
        _delete_=True,
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN2d', requires_grad=False),
        norm_eval=True,
        style='pytorch',
        with_cp=True,
        init_cfg=dict(
            type='Pretrained',
            checkpoint=r50_backbone_checkpoint,
        ),
    ),
    img_neck=dict(
        start_level=1,
    ),
    lifter=dict(
        _delete_=True,
        type='OctreeGaussianLifter',
        num_anchor=9000,
        embed_dims=embed_dims,
        anchor_grad=True,
        feat_grad=False,
        phi_activation=phi_activation,
        semantics=semantics,
        semantic_dim=semantic_dim,
        include_opa=include_opa,
        use_intensity=True,
        occ_annotation='occ3d',
        pc_range=pc_range,
        scale_range=scale_range,
        intensity_opacity_weight=0.35,
        suppress_fallback_opacity=True,
        fallback_opacity=0.03,
        zero_base_semantics=True,
        # V22-C1: build 3x3x3 free-space neighborhood maps once per batch on CUDA.
        build_visibility_neighborhood_maps=True,
        visibility_neighborhood_kernel=3,
        background_gaussian=dict(
            enabled=False,
            num_background=0,
            debug=False,
            debug_interval=100,
            debug_max_print=0,
        ),
        gaussian_probe=dict(
            enabled=True,
            always_compute=True,
            retain_last_result=False,
            debug=False,
            debug_interval=500,
            debug_max_print=0,
            visualize=False,
            visualize_interval=1000000,
            visualize_max_outputs=0,
            visualize_output_dir='work_dirs/gsf_octree_debug_ply',
            startup_log=False,
            grid_range=visibility_pc_range,
            coarse_voxel_size=0.8,
            refined_voxel_size=0.4,
            dda_chunk_size=65536,
            refine_mixed_cells=True,
            refine_temporal_conflict_cells=True,
            max_refined_parents=20000,
            endpoint_margin=0.3,
            min_ray_range=1.0,
            ray_count_tau=3.0,
            strong_free_threshold=0.75,
            temporal_support=dict(
                xyz_dims=(0, 1, 2),
                intensity_dim=3,
                time_lag_dim=4,
                decay_dim=5,
                current_flag_dim=6,
                current_weight=1.0,
                min_point_weight=0.01,
                strong_free_gamma=4.0,
                weak_free_gamma=2.0,
                mixed_factor=0.7,
                time_bin_size=0.02,
            ),
            octree=dict(
                octree_range=octree_pc_range,
                levels=[3.2, 1.6, 0.8, 0.4],
                min_points_by_level={3.2: 20, 1.6: 12, 0.8: 7, 0.4: 3},
                min_weighted_support_by_level={3.2: 12.0, 1.6: 8.0, 0.8: 4.0, 0.4: 2.0},
                max_normal_rms_by_level={3.2: 0.12, 1.6: 0.09, 0.8: 0.07, 0.4: 0.05},
                max_normal_scale_by_level={3.2: 0.25, 1.6: 0.16, 0.8: 0.10, 0.4: 0.06},
                max_temporal_conflict_ratio=0.35,
                support_tau=10.0,
                fit_sigma=0.12,
                min_opacity=0.10,
                max_opacity=0.95,
                free_overlap_reject=0.35,
                max_gaussians=6400,
                # V24-G: only coarse, broad, low and near-horizontal surfaces
                # are forced from 3.2 m to 1.6 m.  This is a batched GPU mask
                # inside the existing four-level octree; no CPU point fitting,
                # per-Gaussian Python loop, or evaluation-time branch is added.
                ground_refinement=dict(
                    enabled=True,
                    source_levels=[3.2],
                    min_abs_normal_z=0.85,
                    min_mean_z=octree_pc_range[2],
                    max_mean_z=0.60,
                    min_major_scale=0.80,
                    min_minor_scale=0.45,
                ),
                fitter=dict(
                    sigma_scale_factor=2.0,
                    min_gaussian_scale=0.05,
                    max_scale_ratio=0.45,
                    min_normal_scale=0.04,
                    max_normal_scale_ratio=0.10,
                    covariance_epsilon=1e-5,
                ),
            ),
        ),
    ),
    encoder=dict(
        type='GaussianOccEncoder3D',
        anchor_encoder=dict(
            type='SparseGaussian3DEncoder',
            embed_dims=embed_dims,
            include_opa=include_opa,
            semantics=semantics,
            semantic_dim=semantic_dim,
        ),
        norm_layer=dict(type='LN', normalized_shape=embed_dims),
        ffn=dict(
            type='AsymmetricFFN',
            in_channels=embed_dims,
            embed_dims=embed_dims,
            feedforward_channels=embed_dims * 4,
        ),
        deformable_model=dict(
            type='GaussianGAFMambaFeatureAggregation3D',
            embed_dims=embed_dims,
            d_model=embed_dims,
            n_layer=2,
            ssm_cfg=dict(
                d_state=16,
                d_conv=4,
                expand=2,
            ),
            drop_path=0.05,
            drop_out_in_block=0.0,
            rms_norm=False,
            fused_add_norm=False,
            residual_in_fp32=False,
            norm_epsilon=1e-5,
            pc_range=pc_range,
            order_voxel_size=[0.4, 0.4, 0.2],
            order_method='H2HE',
            coor_order='xy',
            inverse=False,
            phi_activation=phi_activation,
            xyz_coordinate=xyz_coordinate,
            use_anchor_embed=True,
            use_pos_embed=True,
            use_source_embed=True,
            num_source_types=4,
            source_embed_scale=1.0,
            residual_scale=0.10,
            learnable_residual_scale=True,
            precompute_order_cache=True,
            debug=False,
            debug_interval=500,
            debug_max_print=0,
            startup_log=False,
            num_cams=6,
            num_levels=4,
            # Checkpoint-compatible V24-I dual-ring sampling:
            # preserve num_offsets=4 and all learned tensor shapes, use the first
            # three learned directions at 0.5x and 1.5x sampling radii.
            num_offsets=4,
            sampling_active_offsets=3,
            sampling_scale_factors=[0.5, 1.5],
            img_feat_channels=embed_dims,
            lidar_feat_dim=6,
            use_lidar_fpc=True,
            lidar_pc_range=pc_range,
            fpc_voxel_size=[0.4, 0.4, 0.4],
            fpc_aggregation='soft',
            fpc_radius=3.2,
            fpc_max_voxels=2048,
            fpc_chunk_size=512,
            offset_radius=[2.0, 2.0, 2.0, 2.0],
            gaf_residual_scale=1.0,
            learnable_gaf_scale=True,
            gaf_apply_layer_indices=[0],
            # Sparse-UVD sampling: use out_dpt_multiscale to weight sparse depth samples.
            # This does not create a dense [B,Cam,C,D,H,W] volume.
            use_uvd_sampling=True,
            depth_channels=int((d_bound[1] - d_bound[0]) / d_bound[2]),
            depth_bound=d_bound,
            num_depth_offsets=3,
            depth_offset_radius=1.0,
            min_depth_prob_weight=0.0,
        ),
        refine_layer=dict(
            type='SparseGaussian3DRefinementModule',
            embed_dims=embed_dims,
            pc_range=pc_range,
            scale_range=scale_range,
            restrict_xyz=True,
            unit_xyz=[3.2, 3.2, 0.8],
            refine_manual=[0, 1, 2],
            phi_activation=phi_activation,
            semantics=semantics,
            semantic_dim=semantic_dim,
            include_opa=include_opa,
            xyz_coordinate=xyz_coordinate,
            semantics_activation='softplus',
            preserve_semantic_prior=True,
            semantic_prior_scale=1.0,
        ),
        spconv_layer=dict(
            _delete_=True,
            type='SparseConv3D',
            in_channels=embed_dims,
            embed_channels=embed_dims,
            pc_range=pc_range,
            grid_size=[0.4, 0.4, 0.4],
            phi_activation=phi_activation,
            xyz_coordinate=xyz_coordinate,
            use_out_proj=True,
        ),
        num_decoder=num_decoder,
        num_single_frame_decoder=num_single_frame_decoder,
        operation_order=[
            'deformable',
            'ffn',
            'norm',
            'refine',
        ] * num_single_frame_decoder + [
            'spconv',
            'norm',
            'deformable',
            'ffn',
            'norm',
            'refine',
        ] * (num_decoder - num_single_frame_decoder),
    ),
    head=dict(
        type='GaussianHead',
        apply_loss_type='last_2',
        auxiliary_voxel_stride=4,
        num_classes=semantic_dim + 1,
        # Key Occ3D-17 debug is off by default. Turn on only for diagnosis.
        debug=False,
        debug_interval=50,
        debug_max_print=0,
        debug_class_ids=(1, 2, 5, 6, 7, 8),
        debug_layer_semantics=False,
        debug_voxel_hist=False,
        debug_gt_voxel_topk=False,
        debug_gt_voxel_topk_k=3,
        debug_max_voxels_per_class=4096,
        use_completion_render_gate=True,
        # C2 + post-Mamba rendered-voxel refinement. Mamba remains on Gaussian
        # tokens; after Gaussian rendering, this lightweight 3D U-Net repairs
        # spatial holes/fragmentation without creating any new Gaussian.
        refine_unet=dict(
            enabled=True,
            grid_shape=occ_size,
            base_channels=16,
            mid_channels=24,
            bottleneck_channels=32,
            visibility_channels=5,
            use_camera_mask_channel=True,
            use_checkpoint=True,
            detach_base_input=True,
            dropout=0.0,
            semantic_residual_init=0.05,
            geometry_residual_init=0.05,
            semantic_strong_free_scale=0.10,
            semantic_weak_free_scale=0.50,
            residual_regularization=0.002,
            geometry_loss_weight=1.0,
            debug=False,
            debug_interval=100,
            debug_max_print=0,
        ),
        empty_args=dict(
            _delete_=True,
            mean=[0, 0, -1.0],
            scale=[80.0, 80.0, 6.4],
        ),
        with_empty=True,
        cuda_kwargs=dict(
            _delete_=True,
            scale_multiplier=3,
            H=occ_size[0], W=occ_size[1], D=occ_size[2],
            pc_min=[-40.0, -40.0, -1.0],
            grid_size=grid_size,
        ),
    ),
)
# Disable dataset raw/coordinate debug during normal runs; keep only the
# model-side small-target semantic debug above.
dataset_coord_debug_off = dict(enabled=False, interval=50, max_print=0, show_matrices=False, show_label_hist=False)
train_dataset_config = dict(
    gt_raw_debug=dataset_gt_raw_debug,
    coord_debug=dataset_coord_debug_off,
    yolo2d_cache=yolo2d_cache_train,
    yolo2d_cache_max_det=yolo2d_cache_max_det,
    yolo2d_cache_score_thr=0.0,
    yolo2d_cache_debug=False,
    yolo2d_cache_debug_max_print=0,
)
val_dataset_config = dict(
    gt_raw_debug=dict(enabled=False),
    coord_debug=dataset_coord_debug_off,
    yolo2d_cache=yolo2d_cache_val,
    yolo2d_cache_max_det=yolo2d_cache_max_det,
    yolo2d_cache_score_thr=0.0,
    yolo2d_cache_debug=False,
    yolo2d_cache_debug_max_print=0,
)

# ========= per-GPU batch size override for Mamba fast iteration =========
# In DistributedDataParallel, this is the batch size on EACH GPU, not global batch size.
# For example:
#   CUDA_VISIBLE_DEVICES=0,1 and train_loader.batch_size=4
#   => each GPU processes 4 frames, global training batch size = 8.
per_gpu_train_batch_size = 2
per_gpu_val_batch_size = 1

train_loader = dict(
    batch_size=per_gpu_train_batch_size,
    num_workers=4,
    shuffle=True,
    pin_memory=True,
    # These two are ignored by dataset/get_dataloader when num_workers == 0.
    # They are left here so you can switch num_workers to 1 without editing code again.
    prefetch_factor=2,
    persistent_workers=True,
)

# Keep validation conservative first.  Training is the part that now uses
# single-GPU batch size 4.  After confirming bs=4 is stable, val can be raised too.
val_loader = dict(
    batch_size=per_gpu_val_batch_size,
    num_workers=4,
    pin_memory=True,
    prefetch_factor=2,
    persistent_workers=True,
)
